### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by AramHakobyan01** [keepsoftware/mt7902-dkms#1]
Hi! I have ASUS Vivobook 16 OLED (M1605) and I need a driver for mt7902 working for linux, do you have any success writing this driver or maybe you have found alternative for this?

**Comment by keepsoftware** [comment]
Hi Aram,

Sorry, I haven't successfully built this driver yet.

**Comment by ar1ja** [comment]
i have the same lappy, ur out of luck lol, get a wifi adapter like `TP-LINK TL-WN725N`, it works, i bought it for just 10 euro, but as per its performance -- its questionable

or well, use ethernet if u can, but if u need wifi that adapter works fine, ive been using it, although it does have an annoying green light so cover it up using like nail polish or smt idk

have fun, and make sure to click the 'watch' button in the repositories main page to see any updates on the development like i have :)

( btw if u get the wifi driver https://aur.archlinux.org/packages/8188eu-dkms seems to work better ( ? ), idk what the logic behind it is but yh )

**Comment by ar1ja** [comment]
> i have the same lappy, ur out of luck lol, get a wifi adapter like `TP-LINK TL-WN725N`, it works, i bought it for just 10 euro, but as per its performance -- its questionable
> 
> or well, use ethernet if u can, but if u need wifi that adapter works fine, ive been using it, although it does have an annoying green light so cover it up using like nail polish or smt idk
> 
> have fun, and make sure to click the 'watch' button in the repositories main page to see any updates on the development like i have :)

another option would b replacing the wifi card or something, but its complicated and annoying so id say stick with the wifi adapter or ethernet while the driver is cooking in development
